server:
  port: ${PORT:8080}

vaadin:
  launch-browser: false

logging:
  level:
    org: error

spring:
  profiles:
    active: @spring.profiles.active@
  mustache:
    check-template-location: false
