file-browser:
  root: C:\Users\sujoy\Documents

vaadin:
  launch-browser: true

logging:
  level:
    org: debug
    com: trace

spring:
  jpa:
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: validate
        jdbc.batch_size: 100
        order_inserts: true
        order_updates: true
        jdbc:
          fetch_size: 400
        format_sql: true
        generate_statistics: false
        hbm2ddl:
          schema-generation:
            script:
              append: false
      jakarta:
        persistence:
          schema-generation:
            create-source: metadata
          scripts:
            action: create
            create-target: hibernate-script.sql
  datasource:
    url: jdbc:postgresql://localhost:5432/app_db
    driverClassName: org.postgresql.Driver
    username: app_user
    password: app_user_pw
  security:
    oauth2:
      client:
        registration:
          file-browser:
            provider: file-browser
            client-id: my-test-client
            client-secret: UTRtYkyYN1nbgdPPbBru1FDVsE8ye5JE
            authorization-grant-type: authorization_code
            scope: openid,profile,email
        provider:
          file-browser:
            issuer-uri: http://localhost:8090/realms/my-test-realm