server:
  port: ${PORT:8080}

vaadin:
  launch-browser: true

logging:
  level:
    org:
      atmosphere: warn

file-browser:
  root: C:\Users\sujoy\Documents

spring:
  mustache:
    check-template-location: false
  security:
    oauth2:
      client:
        registration:
          file-browser:
            provider: file-browser
            client-id: file-browser
            client-secret: OMAVIHOLEuvn48DzvkuCysW1hYMHvyBt
            authorization-grant-type: authorization_code
            scope: openid,profile,email
        provider:
          file-browser:
            issuer-uri: https://keycloak.homedns.pro/realms/homelab